### ISSUE TITLE
Tokens are rendered in headers, but not attributes.

### ISSUE THREAD

**Issue by whosgonna** [rjbs/Email-MIME-Kit#7]
Template tokens can be used in headers for things like setting the To:, From:, Cc:, etc addresses, but does not work for things like file path or file name for attachments.  As a general use case, when creating a report to be emailed, I don't want to keep the report on disk.  Using [File::Temp](https://metacpan.org/pod/File::Temp) is a great way to go about managing the report as a temp file, however there's not a way to configure the path to the file by name.  Other examples can occur when wanting to rename the file dynamically (such as making `report.pdf` to something like `2021-10-01_report.pdf`.

Ideally, I'd have a a manifest like this:
```yaml
attachments:
- type: "[% rpt_type %]"
  path: "[% rpt_path %]"
  attributes:
    filename: "[% rpt_name %]"
```

And corresponding code like this:
```perl
my $email = $kit->assemble({
  rpt_path => 'temp5d0b.pdf',
  rpt_name => $rpt_file_name,
});
```

I'll submit a PR for the change.
